//! The menu-bar item, its settings menu, and the widget's own right-click menu.
//!
//! macOS renders whatever menu was last handed to the status item, so a checkbox
//! built at the wrong moment stays wrong. The menu is rebuilt on every state
//! change *and* when the pointer enters the icon, which is the last moment
//! before a click can open it.

use std::process::Command;
use std::sync::Arc;
use std::time::Duration;

use tauri::image::Image;
use tauri::menu::{CheckMenuItem, Menu, MenuEvent, MenuItem, PredefinedMenuItem, Submenu};
use tauri::tray::{MouseButton, MouseButtonState, TrayIcon, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Manager};
use tauri_plugin_autostart::ManagerExt;

use crate::state::Core;
use crate::store::Store;
use crate::window::{self, Rect, SKINS, WIDGET};

pub const TRAY_ID: &str = "pear-music-widget";

// Menu-bar template images: 'solid' while connected, 'hollow' when the YouTube
// Music API server cannot be reached — so the menu bar itself tells you whether
// the player is up. Generated by build.rs; @2x so they stay crisp at 18pt.
const SOLID: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-solid@2x.png"));
const HOLLOW: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/tray-hollow@2x.png"));

// The bundle differs between th-ch and pear builds, so the launcher tries each
// name in turn.
const MUSIC_APPS: [&str; 3] = ["YouTube Music", "Pear", "Pear Desktop"];

/// pear-desktop and th-ch's build ship the same appId, so one id covers both.
const MUSIC_APP_ID: &str = "com.github.th-ch.youtube-music";

// Finer steps near the top, because that is the range worth having: below
// about 80% the text starts fighting whatever is behind the glass.
const OPACITIES: [u32; 5] = [100, 95, 90, 85, 80];

/// How strongly the cover's colours wash the card. Stored as a fraction, shown
/// by name — "40%" means nothing to look at, whereas "Subtle" does.
const TINTS: [(u32, &str); 5] = [(0, "Off"), (35, "Subtle"), (60, "Medium"), (80, "Strong"), (100, "Vivid")];

const SKIN_LABELS: [(&str, &str); 2] = [("classic", "Classic"), ("stack", "Stack")];

/// A menu is as wide as its widest item, and the now-playing line is the only
/// one whose length we do not control. Budget it in display columns rather than
/// characters: a CJK title counted by `char` is twice as wide as it looks, which
/// is how a track name ended up stretching the menu halfway across the screen.
/// The rest of the menu tops out around 23 columns ("Quit with YouTube Music").
const NOW_PLAYING_COLUMNS: usize = 36;

/// Display columns a character occupies. An approximation of Unicode's East
/// Asian Width — full-width forms and emoji take two, everything else one —
/// which is all a menu needs.
fn columns(c: char) -> usize {
    let code = c as u32;
    let wide = matches!(code,
        0x1100..=0x115F
        | 0x2E80..=0x303E
        | 0x3041..=0x33FF
        | 0x3400..=0x4DBF
        | 0x4E00..=0x9FFF
        | 0xA000..=0xA4CF
        | 0xAC00..=0xD7A3
        | 0xF900..=0xFAFF
        | 0xFE10..=0xFE19
        | 0xFE30..=0xFE6F
        | 0xFF00..=0xFF60
        | 0xFFE0..=0xFFE6
        | 0x1F300..=0x1F64F
        | 0x1F900..=0x1F9FF
        | 0x20000..=0x3FFFD);
    if wide { 2 } else { 1 }
}

/// Trim to a column budget, leaving room for the ellipsis that says so.
fn ellipsize(text: &str, budget: usize) -> String {
    if text.chars().map(columns).sum::<usize>() <= budget {
        return text.to_string();
    }

    let mut out = String::new();
    let mut used = 0;
    for c in text.chars() {
        let width = columns(c);
        if used + width > budget.saturating_sub(1) {
            break;
        }
        out.push(c);
        used += width;
    }
    out.push('…');
    out
}

fn status_label(status: &str) -> &str {
    match status {
        "connected" => "Connected",
        "connecting" => "Connecting…",
        "offline" => "API server unreachable",
        "unauthorized" => "Not authorised",
        "denied" => "Authorisation denied",
        other => other,
    }
}

pub fn open_music_app() {
    let script = MUSIC_APPS
        .iter()
        .map(|name| format!("open -a \"{name}\""))
        .collect::<Vec<_>>()
        .join(" || ");
    let _ = Command::new("sh").arg("-c").arg(script).spawn();
}

/// Ask the music app to quit, then run `done` — whether or not it worked.
///
/// Addressed by bundle id, not by name: `application "YouTube Music" is running`
/// answers false even while it is running, which silently turns the guard into a
/// no-op. By id it is accurate, and a guarded quit on a closed app does nothing
/// rather than launching it.
///
/// `quit` is an Apple event, so the first use raises the one-time "wants to
/// control" prompt. If that is denied the script just fails and we still quit.
fn quit_music_app_then(app: AppHandle) {
    tauri::async_runtime::spawn(async move {
        let target = format!("application id \"{MUSIC_APP_ID}\"");
        let script = format!("if {target} is running then quit {target}");

        // Never hang the quit on a blocked or slow Apple event.
        let _ = tokio::time::timeout(
            Duration::from_secs(4),
            tokio::task::spawn_blocking(move || {
                let _ = Command::new("osascript").arg("-e").arg(script).output();
            }),
        )
        .await;

        crate::quit(&app);
    });
}

// ------------------------------------------------------------------- pieces

fn skin_submenu(
    app: &AppHandle,
    id_prefix: &str,
    label: &str,
    current: &str,
) -> tauri::Result<Submenu<tauri::Wry>> {
    let items: Vec<CheckMenuItem<tauri::Wry>> = SKIN_LABELS
        .iter()
        .map(|(key, text)| {
            CheckMenuItem::with_id(app, format!("{id_prefix}:{key}"), text, true, *key == current, None::<&str>)
        })
        .collect::<tauri::Result<_>>()?;

    let refs: Vec<&dyn tauri::menu::IsMenuItem<tauri::Wry>> =
        items.iter().map(|item| item as &dyn tauri::menu::IsMenuItem<tauri::Wry>).collect();
    Submenu::with_items(app, label, true, &refs)
}

fn opacity_submenu(app: &AppHandle, current: f64) -> tauri::Result<Submenu<tauri::Wry>> {
    let selected = (current * 100.0).round() as u32;
    let items: Vec<CheckMenuItem<tauri::Wry>> = OPACITIES
        .iter()
        .map(|pct| {
            CheckMenuItem::with_id(
                app,
                format!("opacity:{pct}"),
                format!("{pct}%"),
                true,
                *pct == selected,
                None::<&str>,
            )
        })
        .collect::<tauri::Result<_>>()?;

    let refs: Vec<&dyn tauri::menu::IsMenuItem<tauri::Wry>> =
        items.iter().map(|item| item as &dyn tauri::menu::IsMenuItem<tauri::Wry>).collect();
    Submenu::with_items(app, "Opacity", true, &refs)
}

fn tint_submenu(app: &AppHandle, current: f64) -> tauri::Result<Submenu<tauri::Wry>> {
    let selected = (current * 100.0).round() as u32;
    let items: Vec<CheckMenuItem<tauri::Wry>> = TINTS
        .iter()
        .map(|(pct, label)| {
            CheckMenuItem::with_id(app, format!("tint:{pct}"), label, true, *pct == selected, None::<&str>)
        })
        .collect::<tauri::Result<_>>()?;

    let refs: Vec<&dyn tauri::menu::IsMenuItem<tauri::Wry>> =
        items.iter().map(|item| item as &dyn tauri::menu::IsMenuItem<tauri::Wry>).collect();
    Submenu::with_items(app, "Cover tint", true, &refs)
}

fn always_on_top_item(app: &AppHandle, checked: bool) -> tauri::Result<CheckMenuItem<tauri::Wry>> {
    CheckMenuItem::with_id(app, "alwaysOnTop", "Always on top", true, checked, None::<&str>)
}

// -------------------------------------------------------------------- menus

/// The menu-bar settings menu. Built fresh every time, so it can never show a
/// stale checkbox.
pub fn build_tray_menu(app: &AppHandle) -> tauri::Result<Menu<tauri::Wry>> {
    let core = app.state::<Arc<Core>>();
    let store = app.state::<Arc<Store>>();
    let snapshot = core.snapshot();

    let now_playing = snapshot
        .song
        .as_ref()
        .map(|song| format!("{} — {}", song.title, song.artist))
        .unwrap_or_else(|| "Nothing playing".into());
    let now_playing = ellipsize(&now_playing, NOW_PLAYING_COLUMNS);

    let widget = app.get_webview_window(WIDGET);
    let widget_alive = widget.is_some();
    let widget_visible = widget
        .as_ref()
        .map(|w| w.is_visible().unwrap_or(false))
        .unwrap_or(false);

    let opacity = store.get(|s| s.opacity);
    let tint = store.get(|s| s.tint);
    let always_on_top = store.get(|s| s.always_on_top);
    let open_at_login = app.autolaunch().is_enabled().unwrap_or(false);

    Menu::with_items(
        app,
        &[
            &MenuItem::with_id(app, "nowPlaying", now_playing, false, None::<&str>)?,
            &MenuItem::with_id(app, "status", status_label(&snapshot.status), false, None::<&str>)?,
            &PredefinedMenuItem::separator(app)?,
            &CheckMenuItem::with_id(
                app,
                "showWidget",
                "Show floating widget",
                widget_alive,
                widget_visible,
                None::<&str>,
            )?,
            &always_on_top_item(app, always_on_top)?,
            &skin_submenu(app, "skin", "Skin", &window::skin_of(&store))?,
            &skin_submenu(app, "panelSkin", "Dropdown skin", &window::panel_skin_of(&store))?,
            &tint_submenu(app, tint)?,
            &opacity_submenu(app, opacity)?,
            &MenuItem::with_id(app, "reset", "Reset size and position", widget_alive, None::<&str>)?,
            &PredefinedMenuItem::separator(app)?,
            &CheckMenuItem::with_id(app, "openAtLogin", "Open at login", true, open_at_login, None::<&str>)?,
            &MenuItem::with_id(app, "reconnect", "Reconnect", true, None::<&str>)?,
            &PredefinedMenuItem::separator(app)?,
            &MenuItem::with_id(app, "quit", "Quit", true, Some("CmdOrCtrl+Q"))?,
            &MenuItem::with_id(app, "quitWithMusic", "Quit with App", true, None::<&str>)?,
        ],
    )
}

/// Right-click menu for the floating widget itself: the things you would want
/// while looking at it, minus the app-level plumbing that belongs in the tray.
///
/// Deliberately no "Dropdown skin" — every item here acts on the window you
/// right-clicked, and the dropdown has its own menu for its own layout.
pub fn build_widget_menu(app: &AppHandle) -> tauri::Result<Menu<tauri::Wry>> {
    let store = app.state::<Arc<Store>>();
    let alive = app.get_webview_window(WIDGET).is_some();

    Menu::with_items(
        app,
        &[
            &skin_submenu(app, "skin", "Skin", &window::skin_of(&store))?,
            &tint_submenu(app, store.get(|s| s.tint))?,
            &opacity_submenu(app, store.get(|s| s.opacity))?,
            &always_on_top_item(app, store.get(|s| s.always_on_top))?,
            &PredefinedMenuItem::separator(app)?,
            &MenuItem::with_id(app, "reset", "Reset size and position", alive, None::<&str>)?,
            &MenuItem::with_id(app, "hideWidget", "Hide widget", alive, None::<&str>)?,
            &PredefinedMenuItem::separator(app)?,
            &MenuItem::with_id(app, "quit", "Quit", true, Some("CmdOrCtrl+Q"))?,
            &MenuItem::with_id(app, "quitWithMusic", "Quit with App", true, None::<&str>)?,
        ],
    )
}

/// Right-click menu for the dropdown. Only what applies to it: opacity, always
/// on top and the reset all act on the floating widget, so they stay out of it.
pub fn build_panel_menu(app: &AppHandle) -> tauri::Result<Menu<tauri::Wry>> {
    let store = app.state::<Arc<Store>>();

    Menu::with_items(
        app,
        &[
            &skin_submenu(app, "panelSkin", "Dropdown skin", &window::panel_skin_of(&store))?,
            &tint_submenu(app, store.get(|s| s.tint))?,
            &PredefinedMenuItem::separator(app)?,
            &MenuItem::with_id(app, "quit", "Quit", true, Some("CmdOrCtrl+Q"))?,
            &MenuItem::with_id(app, "quitWithMusic", "Quit with App", true, None::<&str>)?,
        ],
    )
}

// ------------------------------------------------------------------ actions

pub fn set_skin(app: &AppHandle, skin: &str) {
    // The renderer's IPC lands on a worker thread, so the window work is hopped
    // to the main thread as one closure — the aspect lock has to be released,
    // the window resized and the lock re-applied in that order.
    let (handle, layout) = (app.clone(), skin.to_string());
    let _ = app.run_on_main_thread(move || {
        if let Some(widget) = handle.get_webview_window(WIDGET) {
            window::apply_skin(&handle, &widget, &layout);
        }
    });

    let core = app.state::<Arc<Core>>().inner().clone();
    core.update(|state| state.skin = skin.to_string());

    let spawned = Arc::clone(&core);
    tauri::async_runtime::spawn(async move { spawned.refresh_upnext().await });
    refresh(app);
}

pub fn set_panel_skin(app: &AppHandle, skin: &str) {
    let (handle, layout) = (app.clone(), skin.to_string());
    let _ = app.run_on_main_thread(move || crate::panel::apply_panel_skin(&handle, &layout));

    let core = app.state::<Arc<Core>>().inner().clone();
    core.update(|state| state.panel_skin = skin.to_string());

    let spawned = Arc::clone(&core);
    tauri::async_runtime::spawn(async move { spawned.refresh_upnext().await });
    refresh(app);
}

pub fn handle_menu(app: &AppHandle, event: MenuEvent) {
    let id = event.id().0.as_str();
    let store = app.state::<Arc<Store>>().inner().clone();
    let widget = app.get_webview_window(WIDGET);

    match id {
        "showWidget" => {
            if let Some(widget) = &widget {
                if widget.is_visible().unwrap_or(false) {
                    let _ = widget.hide();
                } else {
                    // Showing it must not steal focus from whatever you were doing.
                    let _ = widget.show();
                }
            }
        }
        "hideWidget" => {
            if let Some(widget) = &widget {
                let _ = widget.hide();
            }
        }
        "alwaysOnTop" => {
            let next = !store.get(|s| s.always_on_top);
            store.update(|s| s.always_on_top = next);
            if let Some(widget) = &widget {
                let _ = widget.set_always_on_top(next);
            }
        }
        "reset" => {
            if let Some(widget) = &widget {
                window::reset_window(app, widget);
            }
        }
        "openAtLogin" => {
            let enabled = app.autolaunch().is_enabled().unwrap_or(false);
            let _ = if enabled {
                app.autolaunch().disable()
            } else {
                app.autolaunch().enable()
            };
        }
        "reconnect" => crate::ws::retry(app),
        "quit" => crate::quit(app),
        "quitWithMusic" => quit_music_app_then(app.clone()),
        other => {
            if let Some(skin) = other.strip_prefix("skin:") {
                if SKINS.contains(&skin) {
                    set_skin(app, skin);
                }
            } else if let Some(skin) = other.strip_prefix("panelSkin:") {
                if SKINS.contains(&skin) {
                    set_panel_skin(app, skin);
                }
            } else if let Some(pct) = other.strip_prefix("tint:") {
                if let Ok(pct) = pct.parse::<f64>() {
                    let tint = pct / 100.0;
                    store.update(|s| s.tint = tint);
                    // The wash is mixed in the renderer, so the strength has to
                    // reach it like any other piece of state.
                    app.state::<Arc<Core>>().update(|state| state.tint = tint);
                }
            } else if let Some(pct) = other.strip_prefix("opacity:") {
                if let Ok(pct) = pct.parse::<f64>() {
                    let opacity = pct / 100.0;
                    store.update(|s| s.opacity = opacity);
                    if let Some(widget) = &widget {
                        crate::macos::set_alpha(widget, opacity);
                    }
                }
            }
        }
    }

    refresh(app);
}

// --------------------------------------------------------------------- icon

fn icon(connected: bool) -> tauri::Result<Image<'static>> {
    Image::from_bytes(if connected { SOLID } else { HOLLOW })
}

/// The icon's rectangle in logical points, which is what the panel positions
/// itself in.
///
/// Tauri hands this over as an untagged `Position`/`Size` that may be either
/// scale, so resolve it in two steps: guess the display with the primary
/// monitor's scale, then convert for real against the display the icon is
/// actually on. On a single-display Mac the two are the same; on a mixed-DPI
/// setup with the menu bar on the secondary display, the second pass is what
/// keeps the dropdown under the icon.
fn icon_rect(app: &AppHandle, position: tauri::Position, size: tauri::Size) -> Rect {
    let guess = app
        .primary_monitor()
        .ok()
        .flatten()
        .map(|monitor| monitor.scale_factor())
        .unwrap_or(1.0);
    let physical = position.to_physical::<f64>(guess);

    let scale = app
        .monitor_from_point(physical.x, physical.y)
        .ok()
        .flatten()
        .map(|monitor| monitor.scale_factor())
        .unwrap_or(guess);

    let position = position.to_logical::<f64>(scale);
    let size = size.to_logical::<f64>(scale);
    Rect {
        x: position.x,
        y: position.y,
        width: size.width,
        height: size.height,
    }
}

pub fn create(app: &AppHandle) -> tauri::Result<TrayIcon> {
    TrayIconBuilder::with_id(TRAY_ID)
        .icon(icon(false)?)
        .icon_as_template(true)
        .menu(&build_tray_menu(app)?)
        // Left click drops down the player; right click opens settings.
        .show_menu_on_left_click(false)
        // No `on_menu_event` here on purpose. The builder's global handler
        // already receives this menu's events *and* the widget's popup menu,
        // so registering here too would run every item twice — which is
        // invisible for the idempotent items and silently cancels the toggles.
        .on_tray_icon_event(|tray, event| {
            let app = tray.app_handle();
            match event {
                TrayIconEvent::Click {
                    button: MouseButton::Left,
                    button_state: MouseButtonState::Up,
                    rect,
                    ..
                } => {
                    crate::panel::toggle(app, icon_rect(app, rect.position, rect.size));
                }
                // The last moment before a right click can open the menu: make
                // sure the checkboxes describe the world as it is now.
                TrayIconEvent::Enter { .. } => refresh(app),
                _ => {}
            }
        })
        .build(app)
}

/// Re-icon, re-tooltip and rebuild the settings menu against current state.
///
/// Callers include the realtime task, so this hops to the main thread: building
/// an NSMenu anywhere else is undefined, and a menu built on a worker thread is
/// exactly the kind of fault that shows up as a status item that has stopped
/// opening rather than as a crash.
pub fn refresh(app: &AppHandle) {
    let handle = app.clone();
    let _ = app.run_on_main_thread(move || refresh_now(&handle));
}

fn refresh_now(app: &AppHandle) {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    let Some(core) = app.try_state::<Arc<Core>>() else {
        return;
    };
    let snapshot = core.snapshot();

    // Hollow glyph whenever we cannot reach YouTube Music.
    if let Ok(image) = icon(snapshot.status == "connected") {
        let _ = tray.set_icon(Some(image));
        let _ = tray.set_icon_as_template(true);
    }

    let tooltip = match &snapshot.song {
        Some(song) => format!("{} — {}", song.title, song.artist),
        None => format!(
            "Pear Music Widget — {}",
            status_label(&snapshot.status)
        ),
    };
    let _ = tray.set_tooltip(Some(tooltip));

    if let Ok(menu) = build_tray_menu(app) {
        let _ = tray.set_menu(Some(menu));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn budgets_by_width_not_character_count() {
        // 20 CJK characters are 40 columns, so they do not fit in 36.
        let cjk = "海棠果孔雀最好的我動態歌詞很長的標題名字";
        let trimmed = ellipsize(cjk, NOW_PLAYING_COLUMNS);
        assert!(trimmed.ends_with('…'));
        assert!(trimmed.chars().map(columns).sum::<usize>() <= NOW_PLAYING_COLUMNS);
        // Counted by `char` this would have passed straight through untouched.
        assert!(trimmed.chars().count() < cjk.chars().count());
    }

    #[test]
    fn leaves_anything_that_already_fits() {
        assert_eq!(ellipsize("Nothing playing", NOW_PLAYING_COLUMNS), "Nothing playing");
        let exact = "a".repeat(NOW_PLAYING_COLUMNS);
        assert_eq!(ellipsize(&exact, NOW_PLAYING_COLUMNS), exact);
    }

    #[test]
    fn a_mixed_title_is_measured_in_columns() {
        assert_eq!(columns('a'), 1);
        assert_eq!(columns('海'), 2);
        assert_eq!(columns('「'), 2);
        let mixed = ellipsize("最好的我 (50 Feet) 「想愛不能愛的哀愁」【動態歌詞】", NOW_PLAYING_COLUMNS);
        assert!(mixed.chars().map(columns).sum::<usize>() <= NOW_PLAYING_COLUMNS);
    }
}
